server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false   #是否要注册到其他Eureka Server实例
    fetch-registry: false         # 是否要从其他Eureka Server实例获取数据
    service-url:
      defaultZone: http://localhost:8761/eureka/
