server:
  port: 8000
spring:
  application:
    name: yelp-provider-usc                               # 指定注册到eureka server上的服务名称，对于用户服务中心
eureka:
  client:
    service-url:
      default-Zone: http://localhost:8761/eureka/         # 指定eureka server通信地址，注意/eureka/不能少
    instance:
      prefer-ip-address: true                             # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server

