server:
  port: 8010
spring:
  application:
    name: yelp-client-web-manage
eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8761/eureka/,http://localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

yelp-provider-usc:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#ribbon:
#  eager-load:
#    enabled: true   #配置饥饿加载，让Ribbon在应用启动时就初始化
#      clients: yelp-provider-usc   # 多个用,分隔

